# for ngmix
#     gaussian psf
#     exponential galaxy

name: "nsim-geg01"

psf_model: "gauss"
psf_T: 4.0
psf_shape: [0.0, 0.0]

obj_model: "exp"
obj_T_mean: 16.0
obj_T_sigma_frac: 0.3

obj_counts_mean: 100.0
obj_counts_sigma_frac: 0.3

shear: [0.01,0.0]

nsub: 16
