run: "nfit-08"
fitter: "isample"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

# images are "noise free" but there is some noise in the image
# and whitening has been done
noisefree: False

gdrun: "nbc-sva1-004"

# number per g number, index 0-1
nf: 600

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 1300

psf_model: "em3"

# really nail the psf
psf_em_ntry: 2000
psf_em_maxiter: 50000
psf_em_tol: 5.0e-6

# in arcsec
psf_fwhm_guess: 0.9

fit_model: "exp"
trim_image: False
trim_nsigma: 5

isample_pars:
    sampler: "T"

    # first iteration 500, next 2000
    # 500 gives 20% slowdown, 1000 40%
    # 500 gives efficiency 0.19 +/- 0.06, 1000 0.22 +/-  0.07
    nsample: [500,2000]
    ifactor: 1.0
    df: 2.1
    min_err: [1.0e-4,1.0e-4,1.0e-3,1.0e-3,1.0e-4,1.0e-4]
    max_err: [1.0,1.0,1.0,1.0,1.0,1.0]

    # number of tries for max fitter
    max_fitter: "lm"
    max_tries: 4

# lm with my covariance
max_pars:
    method: 'lm'
    ntry: 4
    cov_h: 1.0e-3
    cov_m: 5.0
    lm_pars:
        maxfev: 4000


do_shear: True

use_logpars: True

use_cen_prior: True
# pixel scale is 0.27''
cen_width: 0.07

# from fitting to all cosmos galaxies in galsim data
g_prior_type: "ba"
g_prior_sigma: 0.3
g_prior_during: True

T_prior_type: "Normal"
T_prior_pars: [-1.13, 1.00]

# tail of normal
counts_prior_type: "TruncatedNormal"
counts_prior_pars: [1.8, 2.2, 4.15, 12.0]

# minutes
checkpoints: [0,10,20,30,40,50,60,70,80,90,100,110]
