fitter: "ngmix"

nwalkers: 80
burnin: 400
nstep: 800
mca_a: 2.0

psf_ntry: 3
psf_model: "em2"
psf_maxiter: 500
psf_tol: 5.0e-4

# at least one band must have psf s/n > this
# we won't fit other models if the s/n is too low
# this might be tweaked depending on how many bands
# and images you have in the stack.
min_psf_s2n: 0.0

# should work with these sims I think
region: "seg_and_sky"

# in arcsec.  We don't expect any offset
psf_offset_max: 0.25

max_box_size: 192

fit_types: ['psf','simple']

simple_models: ['exp']
do_pqr: True
do_lensfit: False

# makes no sense for a single image
reject_outliers: False

use_cen_prior: True
cen_width: 0.27

# from fitting to all cosmos galaxies in galsim data
g_prior_types: ["cosmos-exp"]

# still want true here even if using the coadd guess,
# in case the guess is broken
draw_g_prior: True

T_prior_types: ["cosmos_exp"]

# we cannot use cosmos because the fluxes were rescaled
counts_prior_types: ["flat"]
counts_prior_pars: [ [0.0, 10000.0] ]

# just measure the coadd
do_coadd: True

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

checkpoints: [0,10,30,60,90]

make_plots: True
debug: 0
