run: "sfit-c01"
fitter: "isample"

# min s2n_w from gauss fit before we do regular fit
min_s2n: 4.0

noisefree: False

# images are "noise free" but there is some noise in the image and whitening
# has been done.  calculate from a border region

calc_weight: False

gdrun: "nbc-sva1-004"

# number per g number, index 0-1
nf: 600

# shear numbers 0-7
ng: 8

# size of processing chunks
nper: 500

max_pars:
    method: 'lm'
    ntry: 4

    #use_fracdev_grid: False
    fracdev_range: [-1.2,2.0]

    lm_pars:
        maxfev: 4000

psf_pars:
    model: "turb"
    ntry: 20
    fwhm_guess: 0.9
    addnoise: 0.0001

isample_pars:

    nsample: [2000]
    ifactor: 1.0
    df: 2.1
    min_err: [1.0e-4,1.0e-4,1.0e-3,1.0e-3,1.0e-4,1.0e-4]
    max_err: [1.0,1.0,1.0,1.0,1.0,1.0]

    cov_pars:
        h: 1.0e-3
        m: 5.0


model_pars:
    model: "cm"

    joint_prior:
        cen_width: 0.4
        g_prior_pars: [1.0, 4222.89, 0.0716121, 0.577453]

        TF_prior_run: "sfit-noisefree-c01"
        TF_partype: "log_TF"

        fracdev_prior_run: "sfit-noisefree-c01"
        fracdev_partype: "log_F_fracdev"

fracdev_grid:
    min: -1.0
    max:  1.1
    num:  22

do_shear: True

use_logpars: True
